"""user_area_assignments

Revision ID: 768e1b187e64
Revises: 9f6f9d7fd1f2
Create Date: 2026-06-23 21:45:35.428274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768e1b187e64'
down_revision = '9f6f9d7fd1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_area_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_area_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_area_assignments_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_area_assignments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_index(batch_op.f('ix_areas_name'))
        batch_op.create_index(batch_op.f('ix_areas_name'), ['name'], unique=True)

    with op.batch_alter_table('nfc_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uid'))
        batch_op.drop_index(batch_op.f('ix_nfc_tags_uid'))
        batch_op.create_index(batch_op.f('ix_nfc_tags_uid'), ['uid'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'areas', ['current_area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('nfc_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfc_tags_uid'))
        batch_op.create_index(batch_op.f('ix_nfc_tags_uid'), ['uid'], unique=False)
        batch_op.create_index(batch_op.f('uid'), ['uid'], unique=True)

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_name'))
        batch_op.create_index(batch_op.f('ix_areas_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('user_area_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_area_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_area_assignments_area_id'))

    op.drop_table('user_area_assignments')
    # ### end Alembic commands ###
