"""init

Revision ID: 7aca60f75e74
Revises: 
Create Date: 2026-04-10 12:42:45.443026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aca60f75e74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_mac'), ['mac'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('recv_ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('uptime_ms', sa.BigInteger(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('feat', sa.Text(), nullable=True),
    sa.Column('delta', sa.Text(), nullable=True),
    sa.Column('samples', sa.Text(), nullable=True),
    sa.Column('win_ms', sa.Integer(), nullable=True),
    sa.Column('step_ms', sa.Integer(), nullable=True),
    sa.Column('t_ms', sa.Integer(), nullable=True),
    sa.Column('parse_ok', sa.Boolean(), nullable=False),
    sa.Column('raw_or_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_device_created_at', ['device_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_recv_ts_ms'), ['recv_ts_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)
        batch_op.create_index('ix_events_type_recv_ts', ['type', 'recv_ts_ms'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_type_recv_ts')
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_recv_ts_ms'))
        batch_op.drop_index(batch_op.f('ix_events_device_id'))
        batch_op.drop_index('ix_events_device_created_at')

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_mac'))

    op.drop_table('devices')
    # ### end Alembic commands ###
